### ISSUE TITLE
Are you looking for contributors to help in the development?

### ISSUE THREAD

**Issue by kinggoesgaming** [codersauce/red#5]
Been watching the youtube series, and am interested in spending a couple hours each week helping in this project, if you are willing to accept help 🙂

**Comment by fcoury** [comment]
Of course, I would love some help! Feel free to clone the project, work on it and submit pull requests.

Also if you'd like to discuss the project and contributions further you can join our Discord server here: https://discord.gg/N7XVd4Ng38.

Thank you!
