### ISSUE TITLE
Errors when running cargo install --path .

### ISSUE THREAD

**Issue by Bxnni78187** [codersauce/red#52]
I cant cargo install the project. i am getting 7 errors when compiling. 
![Screenshot 2024-07-13 121711](https://github.com/user-attachments/assets/2ec5f196-2a42-40b0-a953-3848bdfd873a)
![Screenshot 2024-07-13 121806](https://github.com/user-attachments/assets/7f761cd4-bc3e-4208-af5e-c65a0f3e184d)
os: windows 11

**Comment by fcoury** [comment]
Apparently those are Windows specific errors, as we are relying on the nix crate for the `Suspend` action. The easiest way to make this work is to make this optional inside a [https://doc.rust-lang.org/reference/conditional-compilation.html](conditional compilation) block.

Would you be interested in contributing this patch?

**Comment by Bxnni78187** [comment]
Yes please

**Comment by Bxnni78187** [comment]
.

**Comment by fcoury** [comment]
I meant if you could help the project by fixing those errors in Windows. I don't have easy access to a Windows machine to test them, since I use macOS and Linux.

Makes sense?

**Comment by Bxnni78187** [comment]
i could do that
